### ISSUE TITLE
Open vs closed network functionality

### ISSUE THREAD

**Issue by johnbillion** [jeremyfelt/multisite-notes#6]
Functionality which could change depending on whether a network is open/closed/trusted/untrusted. Or depending on the network type, which we're discussing in #5.

Starting list:
- access to plugins screen
- access to all themes on the network (remove enable/disable themes)
- add users without requiring them to click a confirmation link
- search for users by username (instead of requiring knowing their email address)
- forcibly close user registration
- remove spam functionality from users and sites screens
- remove 'registered' field for users?
- wp_is_large_network() - affected by default?
- user welcome email
- site welcome email
- first post on a blog
- notification emails which get sent to the site admin
- unlimited total file size
- unlimited upload file size
- file types would fall back to single site allowed file types
- Allow site administrators to add new users to their site via the "Users → Add New" page.
- NEWBLOGREDIRECT - don't redirect to signup page if trusted network
- unfiltered html (but probably not)

**Comment by earnjam** [comment]
I feel like you could have multiple levels of access to themes and plugins and you might want to mix and match the two depending on your network. For each of them, you could have them operate how themes do now, or how plugins do now. But with plugins having the additional option of being network activated. 

##### Themes:
- Access to all themes **_(This would be a new feature)_**
- No access to themes **_(This would be a new feature)_**
- Access to only `network enabled` themes and themes that have been `enabled` specifically for that site _(Existing functionality)_

##### Plugins:
- No access to plugins _(Existing functionality)_
- Access to all plugins _(Existing functionality)_
- Access to only `network enabled` plugins and plugins that have been `enabled` specifically for that site **_(This would be a new feature)_**
- Network activated - turned on for all sites on the network with no ability to disable by individual site admins _(Existing functionality)_

"Enabled" and "activated" are very close in terminology and they can be easily confused, so we might want to consider the verbiage, but I can easily see a use case for each type of access.

**Comment by earnjam** [comment]
Also curious how `wp_is_large_network()` would be affected by the network being open/closed/trusted/untrusted. My understanding is that function is based entirely on size ( > 10k users or > 10k sites)

**Comment by cfoellmann** [comment]
@earnjam the sites count is just shared between all networks. there is no difference in performance between 15k sites in 1 network || 15k sites in 10 network || 15k sites in 100 networks! Somewhere in there http://wordpress.tv/2014/07/26/john-james-jacoby-multisite-and-multi-network/ - watched that one last week

**Comment by earnjam** [comment]
Yeah, I guess my question is more why would the nature of the network (open/closed/etc) affect the determination of whether it's large or not.

**Comment by jeremyfelt** [comment]
If you're reading this comment, you would be perfect to—after becoming familiar with the material in this issue—chime in on the new thread at https://make.wordpress.org/core/2015/02/18/multisite-objective-defining-network-types/ with your :thought_balloon:

:+1: :zap:

I'm going to close this as a way of moving the conversation. :)
