### ISSUE TITLE
plugins/themes on a per-network basis

### ISSUE THREAD

**Issue by cfoellmann** [jeremyfelt/multisite-notes#9]
Allow a structure like

```
.
+-- wp-content
|   +-- networks
|       +-- network.1
|           +-- plugins
|           +-- themes
|       +-- network.2
|           +-- plugins
|           +-- themes
|       +-- network.{site_id}
|           +-- plugins
|           +-- themes
```

to provide themes/plugins only to specific networks within the installation

**Comment by earnjam** [comment]
I think the problem with something like that is sharing a theme/plugin cross-network. So you'd end up duplicate code for something you wanted to use in multiple places.

I'd keep them all in single themes/plugins folders as they are now, but make them optionally available through a value stored in the database. Similar to how themes work with individual sites now, but for networks.

**Comment by cfoellmann** [comment]
you could symlink plugins/themes across networks
